name: Docker Image CI

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep -Po '(?<=^version = ")[^"]*' tut2app/pyproject.toml)
          echo "Project version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Use extracted version
        run: |
          echo "Using the extracted version: ${{env.version}}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64 #,linux/arm64
          context: ./tut2app
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tut2:latest-dev
            ghcr.io/${{ github.repository_owner }}/tut2:${{env.version}}-${{GITHUB_SHA}}-dev
            
